parser: babel-eslint
extends: airbnb
env:
  node: true
  es6: true
  jest: true
parserOptions:
  sourceType: "module"
  ecmaFeatures:
    jsx: true
plugins:
  - import
  - node
settings:
  import/resolver: webpack
rules:
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  react/forbid-prop-types: 0
